site_name: "Les algorithmes de bases"
site_url: https://isn-icn-ljm.pagesperso-orange.fr/exp2
#repo_url: https://gitlab.com/ens-fr/exp2
edit_uri: tree/main/docs/
#site_description: Tutoriel pour un IDE et un Terminal dans MkDocs Material 
copyright: |
  Copyleft &#127279 2022 <a href="https://isn-icn-ljm.pagesperso-orange.fr/" target="_blank" rel="noopener">Stéphan Van Zuijlen</a>
docs_dir: docs

nav:
  - "🏡 Accueil": index.md
  - "Sommes en tout genre": sommes.md
  - "Recherche" : recherche.md
  - "Tri" : tri.md
  - "Divers" : divers.md


theme:
    name: material
    custom_dir: my_theme_customizations/
    font: false                     # RGPD ; pas de fonte Google
    language: fr                    # français
    palette:                        # Palettes de couleurs jour/nuit
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: blue
        accent: blue
        toggle:
            icon: material/weather-night
            name: Passer au mode jour
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: indigo
        accent: indigo
        toggle:
            icon: material/weather-sunny
            name: Passer au mode nuit
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.expand
        - navigation.top
        - toc.integrate
        - header.autohide


markdown_extensions:
    - meta
    - abbr
    - def_list                      # Les listes de définition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorés  !!! info "ma remarque"
    - pymdownx.details              #   qui peuvent se plier/déplier.
    - pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surligné==.
    - pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
    - pymdownx.highlight            # Coloration syntaxique du code
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed:               # Volets glissants.  === "Mon volet"
        alternate_style: true 
    - pymdownx.superfences:          # Imbrication de blocs.
        preserve_tabs: true
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:               # Émojis  :boom:
        emoji_index:     !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tasklist:
        custom_checkbox: true
        clickable_checkbox: true
    - pymdownx.arithmatex:
        generic: true
    - toc:
        permalink: ⚓︎
        toc_depth: 3

extra:
    social:
        # - icon: fontawesome/brands/gitlab
        #   link: https://gitlab.com/ens-fr
        #   name: Enseignement en français

        #- icon: fontawesome/brands/discourse
         # link: https://mooc-forums.inria.fr/moocnsi/
         # name: Le forum des enseignants de NSI

        - icon: fontawesome/brands/linux
          link: https://linuxfr.org/
          name: Promouvoir les Logiciels libres

        - icon: fontawesome/brands/wikipedia-w
          link: https://fr.wikipedia.org
          name: L'encyclopédie libre que chacun peut améliorer

        #- icon: fontawesome/solid/paper-plane
        #  link: mailto:prof-bouillot@protonmail.com
        # name: Écrire à l'auteur
    site_url: https://isn-icn-ljm.pagesperso-orange.fr/


plugins:
  - search
  - macros
  - enumerate-headings

extra_javascript:
  - xtra/javascripts/mathjax-config.js                    # MathJax
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - xtra/javascripts/interpreter.js
# - https://unpkg.com/mermaid@8.9.2/dist/mermaid.min.js
# - javascripts/mermaid.js

extra_css:
  - xtra/stylesheets/pyoditeur.css
  - xtra/stylesheets/ajustements.css                      # ajustements
